dist: bionic
sudo: false
language: bash
os:
  - linux

addons:
  apt:
    packages:
      - gperf
      - python
      - python-serial
      - libffi-dev
      - libsdl2-dev
      - gcc-4.8-plugin-dev

before_install:
  - PROJECT_PATH=$(pwd)

script:
  - make --version
  - du -hs
  - unzip -p toolchain/xtensa-esp32-elf-linux64.zip xtensa-esp32-elf-linux64-1.22.0-80-g6c4433a-5.2.0.tar | tar xvf -
  - pip2 install --user -r esp-idf/requirements.txt
  - ./build.sh
  - du -hs

notifications:
  irc:
    channels:
      - "chat.freenode.net#badgeteam-dev"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
